import type { RailRadarLiveData } from '../types/railradar';

export const REFERENCE_TRAINS: Record<string, RailRadarLiveData> = {
  '12625': {
    trainNumber: '12625',
    trainName: 'Kerala SF Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 18,
    train: {
      number: '12625',
      name: 'Kerala SF Express',
      type: 'Superfast Express',
      category: 'Superfast',
      source: { code: 'NDLS', name: 'New Delhi' },
      destination: { code: 'TVC', name: 'Thiruvananthapuram Central' },
      runDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
      distance: 3031,
      duration: 3045,
      avgSpeed: 59.8,
      maxSpeed: 110,
      totalHalts: 47,
    },
    currentLocation: {
      stationCode: 'BZA',
      stationName: 'Vijayawada Junction',
      sequence: 28,
      status: 'departed',
      isHalt: true,
      isDiverted: false,
      isActualPosition: true,
      segmentProgress: 0.62,
      speedKmh: 68.4,
      bearingDegrees: 184,
    },
    previousHalt: {
      stationCode: 'BZA',
      stationName: 'Vijayawada Junction',
      sequence: 28,
      distance: 1785,
    },
    nextHalt: {
      stationCode: 'KMT',
      stationName: 'Khammam',
      sequence: 29,
      distance: 1883,
    },
    exceptions: [],
    platform: '3',
    speed: 68.4,
    segmentProgress: 0.62,
    isLive: true,
    route: [
      {
        sequence: 28,
        stationCode: 'BZA',
        stationName: 'Vijayawada Jn',
        isHalt: true,
        scheduledArrival: '14:15',
        scheduledDeparture: '14:25',
        actualArrival: '14:33',
        actualDeparture: '14:43',
        delayArrival: 18,
        delayDeparture: 18,
        status: 'departed',
        distance: 1785,
        platform: '3',
      },
      {
        sequence: 29,
        stationCode: 'KMT',
        stationName: 'Khammam',
        isHalt: true,
        scheduledArrival: '15:40',
        scheduledDeparture: '15:42',
        actualArrival: null,
        actualDeparture: null,
        status: 'upcoming',
        distance: 1883,
        platform: '2',
      },
      {
        sequence: 30,
        stationCode: 'WL',
        stationName: 'Warangal',
        isHalt: true,
        scheduledArrival: '17:10',
        scheduledDeparture: '17:12',
        actualArrival: null,
        actualDeparture: null,
        status: 'upcoming',
        distance: 1991,
        platform: '2',
      },
      {
        sequence: 31,
        stationCode: 'KZJ',
        stationName: 'Kazipet Jn',
        isHalt: true,
        scheduledArrival: '17:35',
        scheduledDeparture: '17:37',
        actualArrival: null,
        actualDeparture: null,
        status: 'upcoming',
        distance: 2001,
        platform: '1',
      },
      {
        sequence: 32,
        stationCode: 'SC',
        stationName: 'Secunderabad Jn',
        isHalt: true,
        scheduledArrival: '19:00',
        scheduledDeparture: '19:15',
        actualArrival: null,
        actualDeparture: null,
        status: 'upcoming',
        distance: 2133,
        platform: '5',
      },
    ],
  },
  '12760': {
    trainNumber: '12760',
    trainName: 'Charminar SF Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 8,
    train: {
      number: '12760',
      name: 'Charminar SF Express',
      type: 'Superfast Express',
      category: 'Superfast',
      source: { code: 'HYB', name: 'Hyderabad Deccan' },
      destination: { code: 'TBM', name: 'Tambaram' },
      distance: 790,
      duration: 840,
      avgSpeed: 56.4,
      totalHalts: 16,
    },
    currentLocation: {
      stationCode: 'WL',
      stationName: 'Warangal',
      sequence: 4,
      status: 'arrived',
      isHalt: true,
      segmentProgress: 0.35,
      speedKmh: 42.0,
      bearingDegrees: 120,
    },
    previousHalt: {
      stationCode: 'KZJ',
      stationName: 'Kazipet Jn',
      sequence: 3,
    },
    nextHalt: {
      stationCode: 'KMT',
      stationName: 'Khammam',
      sequence: 5,
    },
    exceptions: [],
    platform: '1',
    speed: 42.0,
    segmentProgress: 0.35,
    isLive: true,
    route: [
      {
        sequence: 4,
        stationCode: 'WL',
        stationName: 'Warangal',
        isHalt: true,
        scheduledArrival: '20:45',
        scheduledDeparture: '20:47',
        status: 'arrived',
        platform: '1',
      },
      {
        sequence: 5,
        stationCode: 'KMT',
        stationName: 'Khammam',
        isHalt: true,
        scheduledArrival: '22:03',
        scheduledDeparture: '22:05',
        status: 'upcoming',
        platform: '1',
      },
      {
        sequence: 6,
        stationCode: 'BZA',
        stationName: 'Vijayawada Jn',
        isHalt: true,
        scheduledArrival: '23:45',
        scheduledDeparture: '23:55',
        status: 'upcoming',
        platform: '6',
      },
    ],
  },
  '12919': {
    trainNumber: '12919',
    trainName: 'Malwa SF Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 12,
    train: {
      number: '12919',
      name: 'Malwa SF Express',
      type: 'Superfast Express',
      category: 'Superfast',
      source: { code: 'INDB', name: 'Indore Junction' },
      destination: { code: 'SVDK', name: 'Shri Mata Vaishno Devi Katra' },
      distance: 1640,
      duration: 1720,
      avgSpeed: 57.2,
      totalHalts: 45,
    },
    currentLocation: {
      stationCode: 'UJN',
      stationName: 'Ujjain Junction',
      sequence: 2,
      status: 'departed',
      isHalt: true,
      segmentProgress: 0.45,
      speedKmh: 65.5,
      bearingDegrees: 180,
    },
    previousHalt: {
      stationCode: 'INDB',
      stationName: 'Indore Junction',
      sequence: 1,
    },
    nextHalt: {
      stationCode: 'UJN',
      stationName: 'Ujjain Junction',
      sequence: 2,
    },
    exceptions: [],
    platform: '1',
    speed: 65.5,
    segmentProgress: 0.45,
    isLive: true,
    route: [
      {
        sequence: 1,
        stationCode: 'INDB',
        stationName: 'Indore Junction',
        isHalt: true,
        scheduledArrival: null,
        scheduledDeparture: '23:55',
        status: 'departed',
        platform: '4',
      },
      {
        sequence: 2,
        stationCode: 'UJN',
        stationName: 'Ujjain Junction',
        isHalt: true,
        scheduledArrival: '00:55',
        scheduledDeparture: '01:00',
        status: 'departed',
        platform: '1',
      },
      {
        sequence: 3,
        stationCode: 'MKSM',
        stationName: 'Maksi',
        isHalt: true,
        scheduledArrival: '02:10',
        scheduledDeparture: '02:12',
        status: 'upcoming',
        platform: '3',
      },
    ],
  },
  '12028': {
    trainNumber: '12028',
    trainName: 'Shatabdi Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 0,
    train: {
      number: '12028',
      name: 'Shatabdi Express',
      type: 'Shatabdi',
      category: 'Express',
      source: { code: 'SBC', name: 'KSR Bengaluru' },
      destination: { code: 'MAS', name: 'MGR Chennai Central' },
      distance: 359,
      duration: 300,
      avgSpeed: 71.8,
      totalHalts: 4,
    },
    currentLocation: {
      stationCode: 'KPD',
      stationName: 'Katpadi Junction',
      sequence: 3,
      status: 'departed',
      isHalt: true,
      segmentProgress: 0.72,
      speedKmh: 104.0,
      bearingDegrees: 78,
    },
    previousHalt: {
      stationCode: 'KPD',
      stationName: 'Katpadi Junction',
      sequence: 3,
    },
    nextHalt: {
      stationCode: 'AJJ',
      stationName: 'Arakkonam Junction',
      sequence: 4,
    },
    exceptions: [],
    platform: '2',
    speed: 104.0,
    segmentProgress: 0.72,
    isLive: true,
  },
  '17016': {
    trainNumber: '17016',
    trainName: 'Visakha Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 3,
    train: {
      number: '17016',
      name: 'Visakha Express',
      source: { code: 'SC', name: 'Secunderabad Jn' },
      destination: { code: 'BBS', name: 'Bhubaneswar' },
      distance: 1134,
      totalHalts: 38,
    },
    currentLocation: {
      stationCode: 'BZA',
      stationName: 'Vijayawada Jn',
      sequence: 14,
      status: 'arrived',
      isHalt: true,
      segmentProgress: 0.4,
      speedKmh: 0,
    },
    platform: '1',
    speed: 0,
    segmentProgress: 0.4,
    isLive: true,
  },
  '11013': {
    trainNumber: '11013',
    trainName: 'Mumbai Express',
    startDate: new Date().toISOString().split('T')[0],
    lastUpdatedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    status: 'running',
    delayMinutes: 25,
    train: {
      number: '11013',
      name: 'Mumbai Express',
      source: { code: 'LTT', name: 'Lokmanya Tilak Terminus' },
      destination: { code: 'CBE', name: 'Coimbatore Jn' },
      distance: 1515,
      totalHalts: 32,
    },
    currentLocation: {
      stationCode: 'PUNE',
      stationName: 'Pune Junction',
      sequence: 4,
      status: 'departed',
      isHalt: true,
      segmentProgress: 0.18,
      speedKmh: 45.0,
    },
    platform: '3',
    speed: 45.0,
    segmentProgress: 0.18,
    isLive: true,
  },
};

export const POPULAR_TRAINS = [
  { num: '12625', name: 'Kerala SF Express', route: 'NDLS → TVC' },
  { num: '12760', name: 'Charminar SF Express', route: 'HYB → TBM' },
  { num: '12919', name: 'Malwa SF Express', route: 'INDB → SVDK' },
  { num: '12028', name: 'Shatabdi Express', route: 'SBC → MAS' },
  { num: '17016', name: 'Visakha Express', route: 'SC → BBS' },
  { num: '11013', name: 'Mumbai Express', route: 'LTT → CBE' },
];
